# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'PrestoPay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrestoPay
  # pod 'FontAwesome.swift'

  # add the Firebase pod for Google Analytics
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Analytics', '~> 6.25.0'
  pod 'Firebase/Auth',      '~> 6.25.0'
end
