# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'PrestoPay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrestoPay
  # pod 'FontAwesome.swift'
end
