apiVersion: v1
kind: ConfigMap

metadata:
  name: grafana
  namespace: monitoring

data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - access: proxy
        isDefault: true
        name: prometheus
        type: prometheus
        url: http://prometheus:9090
        version: 1
      - access: proxy
        isDefault: true
        name: loki
        type: loki
        url: http://loki:3100
        version: 1
