apiVersion: v1
kind: ConfigMap

metadata:
  name: fluentd
  namespace: monitoring

data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match **>
      @type loki
      url http://loki:3100
      line_format json
      extra_labels {"service":"api"}
    </match>
