apiVersion: apps/v1
kind: Deployment

metadata:
  name: loki
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: loki

  template:
    metadata:
      labels:
        app: loki

    spec:
      containers:
        - name: loki
          image: grafana/loki:1.5.0
          ports:
            - name: loki
              containerPort: 3100
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
