kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: grafana
  namespace: monitoring

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: loki
  namespace: monitoring

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: prometheus
  namespace: monitoring

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
