apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: elasticsearch
  namespace: monitoring
  labels:
    app: elasticsearch

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 4Gi
