apiVersion: v1
kind: Service

metadata:
  name: elasticsearch
  namespace: monitoring

spec:
  selector:
    app: elasticsearch

  clusterIP: None
  ports:
  - name: rest
    protocol: TCP
    port: 9200
  - name: inter-node
    protocol: TCP
    port: 9300
