apiVersion: v1
kind: Service

metadata:
  name: grafana
  namespace: monitoring

spec:
  selector:
    app: grafana

  type: NodePort
  ports:
    - name: tcp
      protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: Service

metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'

spec:
  selector:
    app: prometheus

  type: NodePort
  ports:
    - name: tcp
      protocol: TCP
      port: 9090
      targetPort: 9090

---

apiVersion: v1
kind: Service

metadata:
  name: loki
  namespace: monitoring

spec:
  selector:
    app: loki

  ports:
  - name: tcp
    protocol: TCP
    port: 3100
    targetPort: 3100

---

apiVersion: v1
kind: Service

metadata:
  name: promtail
  namespace: monitoring

spec:
  selector:
    app: promtail

  ports:
  - name: tcp
    protocol: TCP
    port: 9080
    targetPort: 9080

---

apiVersion: v1
kind: Service

metadata:
  name: kube-state-metrics
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'

spec:
  selector:
    app: kube-state-metrics

  type: NodePort
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service

metadata:
  name: prometheus-node-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'

spec:
  selector:
    app: prometheus
    component: node-exporter

  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp
      protocol: TCP
      port: 9100
      targetPort: 9100
