apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: loki
  namespace: monitoring

spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki

  template:
    metadata:
      labels:
        app: loki

    spec:
      containers:
        - name: loki
          image: grafana/loki:1.5.0
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: loki
              containerPort: 3100
          volumeMounts:
            - name: loki-storage
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: loki-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
