apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: grafana
  namespace: monitoring

spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
        - name: grafana
          image: grafana/grafana:7.0.2
          # imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 300Mi
          ports:
            - name: grafana
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
          env:
            - name: GF_AUTH_BASIC_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-username
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: grafana-password
          command: ["sudo", "chmod", "777", "/var/lib/grafana"]
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources/
            - name: grafana-storage
              mountPath: /var/lib/grafana
      # initContainers:
      #   - name: init-chmod-data
      #     image: grafana/grafana:7.0.2
      #     imagePullPolicy: "IfNotPresent"
      #     command: ["chmod", "777", "/var/lib/grafana"]
      #     volumeMounts:
      #       - name: grafana-storage
      #         mountPath: /var/lib/grafana
      volumes:
        - name: grafana-config
          configMap:
            name: grafana

  volumeClaimTemplates:
    - metadata:
        name: grafana-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
