// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/group/uploader.go

// Package mock_group is a generated GoMock package.
package mock_group

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockGroupUploader is a mock of GroupUploader interface
type MockGroupUploader struct {
	ctrl     *gomock.Controller
	recorder *MockGroupUploaderMockRecorder
}

// MockGroupUploaderMockRecorder is the mock recorder for MockGroupUploader
type MockGroupUploaderMockRecorder struct {
	mock *MockGroupUploader
}

// NewMockGroupUploader creates a new mock instance
func NewMockGroupUploader(ctrl *gomock.Controller) *MockGroupUploader {
	mock := &MockGroupUploader{ctrl: ctrl}
	mock.recorder = &MockGroupUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGroupUploader) EXPECT() *MockGroupUploaderMockRecorder {
	return m.recorder
}

// UploadThumbnail mocks base method
func (m *MockGroupUploader) UploadThumbnail(tx context.Context, data []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadThumbnail", tx, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadThumbnail indicates an expected call of UploadThumbnail
func (mr *MockGroupUploaderMockRecorder) UploadThumbnail(tx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadThumbnail", reflect.TypeOf((*MockGroupUploader)(nil).UploadThumbnail), tx, data)
}
