version: '3.7'

services:
  swagger:
    container_name: presto_pay_swagger
    build:
      context: ./infra/docker/swagger/viewer
    volumes:
      - ./docs/12_backend/21_swagger/apiv1.yaml:/swagger.yaml:cached
    ports:
      - 8000:8080
    environment:
      SWAGGER_JSON: /swagger.yaml

  console:
    container_name: presto_pay_admin
    build:
      context: ./infra/docker/web/admin
      dockerfile: Dockerfile_development
    working_dir: /web/admin
    volumes:
      - ./web/admin:/web/admin:cached
    ports:
      - 8100:3000
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
    command: yarn dev -H 0.0.0.0 -p 3000
