version: '3.7'

services:
  # Application
  proxy:
    container_name: presto_pay_proxy
    build:
      context: ./infra/docker/envoy
      dockerfile: Dockerfile_development
    volumes:
      - ./infra/envoy/development.yaml:/etc/envoy/envoy.yaml:cached
    ports:
      - 8080:8080
      - 8081:9090
    command: envoy -c /etc/envoy/envoy.yaml

  user_api:
    container_name: presto_pay_user_api
    build:
      context: ./infra/docker/api/user
      dockerfile: Dockerfile_development
    working_dir: /go/src/github.com/calmato/presto-pay/api/user
    volumes:
      - ./api/user:/go/src/github.com/calmato/presto-pay/api/user:cached
      - ./secrets:/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GCP_STORAGE_BUCKET_NAME=${GCP_STORAGE_BUCKET_NAME}
    command: realize start

  calc_api:
    container_name: presto_pay_calc_api
    build:
      context: ./infra/docker/api/calc
      dockerfile: Dockerfile_development
    working_dir: /go/src/github.com/calmato/presto-pay/api/calc
    volumes:
      - ./api/calc:/go/src/github.com/calmato/presto-pay/api/calc:cached
      - ./secrets:/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GCP_STORAGE_BUCKET_NAME=${GCP_STORAGE_BUCKET_NAME}
    command: realize start

  batch:
    container_name: presto_pay_batch
    build:
      context: ./infra/docker/api/batch
      dockerfile: Dockerfile_development
    working_dir: /go/src/github.com/calmato/presto-pay/api/batch
    volumes:
      - ./api/batch:/go/src/github.com/calmato/presto-pay/api/batch:cached

  redis:
    container_name: presto_pay_redis
    build:
      context: ./infra/docker/redis

  swagger:
    container_name: presto_pay_swagger
    build:
      context: ./infra/docker/swagger/viewer
    volumes:
      - ./docs/12_backend/21_swagger/apiv1.yaml:/swagger.yaml:cached
    ports:
      - 8000:8080
    environment:
      SWAGGER_JSON: /swagger.yaml

  admin:
    container_name: presto_pay_admin
    build:
      context: ./infra/docker/web/admin
      dockerfile: Dockerfile_development
    working_dir: /web/admin
    volumes:
      - ./web/admin:/web/admin:cached
    ports:
      - 8100:3000
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
    command: yarn dev -H 0.0.0.0 -p 3000
