version: '3.7'

services:
  user_api:
    container_name: presto_pay_user_api
    build:
      context: ./infra/docker/api/user
      dockerfile: Dockerfile_development
    working_dir: /go/src/github.com/calmato/presto-pay/api/user
    volumes:
      - ./api/user:/go/src/github.com/calmato/presto-pay/api/user:cached
      - ./secrets:/secrets:cached
    command: realize start
