openapi: '3.0.0'

info:
  title: Presto Pay
  description: 割り勘アプリ API設計
  version: 0.1.0

servers:
  - url: http://localhost:8080/v1
    description: 開発環境

paths:
  /users:
    post:
      summary: ユーザー登録
      requestBody:
        $ref: '#/components/requestBodies/CreateUser'
      responses:
        '200':
          $ref: '#/components/responses/CreateUser'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/Unkown'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Error:
      title: エラーレスポンス
      type: object
      properties:
        status:
          type: integer
          description: HTTPステータスコード
        code:
          type: integer
          description: エラー管理用ステータスコード
        message:
          type: string
          description: エラーメッセージ
        errors:
          type: array
          description: エラー詳細
          items:
            properties:
              field:
                type: string
              message:
                type: string

  requestBodies:
    CreateUser:
      description: ユーザー登録APIのリクエスト
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: 表示名
              username:
                type: string
                description: ユーザー名
              email:
                type: string
                format: email
                description: メールアドレス
              thumbnail:
                type: string
                description: サムネイル
              password:
                type: string
                format: password
                description: パスワード
              passwordConfirmation:
                type: string
                format: password
                description: パスワード(確認用)
            required:
              - name
              - username
              - email
              - password
              - passwordConfirmation

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unkown:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    CreateUser:
      description: ユーザー登録APIのレスポンス
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                description: ユーザーID
              name:
                type: string
                description: 表示名
              username:
                type: string
                description: ユーザー名
              email:
                type: string
                format: email
                description: メールアドレス
              thumbnail:
                type: string
                description: サムネイル
              createdAt:
                type: string
                format: date-time
                description: 作成日時
              updatedAt:
                type: string
                format: date-time
                description: 更新日時
