# Promtailの設定
server:
  http_listen_address: 127.0.0.1
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

# Lokiへの接続設定
clients:
  - url: http://loki:3100/loki/api/v1/push

# ログ検出対象の設定
scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - user_api:8081
      labels:
        job: syslogs
        __path__: /var/log/*log
