apiVersion: apps/v1
kind: Deployment

metadata:
  name: kibana
  namespace: monitoring

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana

  template:
    metadata:
      labels:
        app: kibana

    spec:
      containers:
        - name: kibana
          image: kibana:7.7.0
          ports:
            - name: kibana
              containerPort: 5601
          resources:
            requests:
              cpu: 50m
              memory: 100m
            limits:
              cpu: 100m
              memory: 200Mi
          env:
          - name: ELASTICSEARCH_URL
            value: "http://elasticsearch:9200"
