apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 4Gi
