#cloud-config

hostname: presto-pay-dev-vm-api01
timezone: Asia/Tokyo
locale: ja_JP.utf8

disable_root: false

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - bash-completion
  - bind-utils
  - chrony
  - containerd.io
  - docker-ce
  - docker-ce-cli
  - epel-release
  - git
  - make
  - net-tools
  - traceroute
  - tree
  - unzip
  - vim
  - wget
  - yum-utils

yum_repos:
  docker-ce-stable:
    name: Docker CE Stable - x86_64
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: 1
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
  docker-ce-stable-source:
    name: Docker CE Stable - Sources
    baseurl: https://download.docker.com/linux/centos/$releasever/source/stable
    enabled: 0
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
  docker-ce-nightly:
    name: Docker CE Nightly - x86_64
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/nightly
    enabled: 0
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
  docker-ce-nightly-source:
    name: Docker CE Nightly - Sources
    baseurl: https://download.docker.com/linux/centos/$releasever/source/nightly
    enabled: 0
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg

ntp:
  enabled: true
  ntp_client: chrony
  config:
    confpath: /etc/chrony.conf
    template: |
      ## template:jinja
      {% if pools -%}# pools{% endif %}
      {% for pool in pools -%}
      pool {{pool}} iburst
      {% endfor %}
      {%- if servers %}# servers
      {% endif %}
      {% for server in servers -%}
      server {{server}} iburst
      {% endfor %}
      port 0
  servers:
    - ntp1.jst.mfeed.ad.jp
    - ntp2.jst.mfeed.ad.jp
    - ntp3.jst.mfeed.ad.jp

manage_resolv_conf: false
resolv_conf:
  nameservers:
    - 1.1.1.1
    - 8.8.8.8

write_files:
  - path: /etc/sysctl.conf
    append: true
    content: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1

runcmd:
  - sed -i -e 's/^(SELINUX=).*$/\1disabled/' /etc/selinux/config
  - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - systemctl disable --now firewalld
  - systemctl enable --now docker
