name: Android Github Action

on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
  push:
    paths:
      - 'naitive/android/**'

jobs:
  test:
    name: Unit Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Unit tests
        working-directory: naitive/android
        run: ./gradlew test

  apk:
    name: Generate APK
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug APK
        working-directory: naitive/android
        run: bash ./gradlew assembleDebug

      - name: Create APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
