name: Android Test with Firebase
on:
  push:
    paths:
      - 'native/android/**'
      - '.github/workflows/ci-android-on-master-branch.yaml'
    branches:
      - master

env:
  ANDROID_SECRET: ${{ secrets.STG_ANDROID_SECRET }}
  GCP_PROJECT_ID: ${{ secrets.STG_GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.STG_GCP_REGION }}

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Create google-services.json
        working-directory: ./native/android/app
        env:
          ANDROID_SECRET: ${{ secrets.STG_ANDROID_SECRET }}
        run: echo -n ${ANDROID_SECRET} > google-services.json

      - name: Build debug APK
        working-directory: native/android
        run: ./gradlew assembleDebug --stacktrace

      - name: Create APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: native/android/app/build/outputs/apk/debug/app-debug.apk

  firebase_test_lab:
    name: Run UI tests with Firebase Test Lab
    needs: build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '281.0.0'
          service_account_email: ${{ secrets.STG_GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.STG_GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure gcloud
        run: |
          gcloud config set project ${GCP_PROJECT_ID}
          gcloud config set run/platform managed
          gcloud config set run/region ${GCP_REGION}

      - name: Run Robo Tests in Firebase Test Lab
        env:
          APP_EMAIL: ${{ secrets.STG_PRESTO_PAY_EMAIL }}
          APP_PASSWORD: ${{ secrets.STG_PRESTO_PAY_PASSWORD }}
        run: |
          gcloud firebase test android run \
            --type robo \
            --app app-debug/app-debug.apk \
            --device model=H8416,version=28 \
            --timeout 20m \
            --no-auto-google-login \
            --robo-directives \
              text:loginEmailField=${APP_EMAIL},\
              text:loginPasswordField=${APP_PASSWORD},\
              click:loginButton=,\
              click:action_people=,\
              click:addGroup=,\
              text:searchEdit=keio,\
              click:done=,\
              text:groupName=GroupTest,\
              click:addFriend=,\
              text:userName=keio,\
              click:floatingActionButton=,\
              text:expenseName=expenseTest,\
              text:amountEdit=amountTest,\
              click:action_person=,\
              click:logoutButton=,\
              ignore:camera=,\
              ignore:thumbnailEdit=,
