name: Android Github Action

on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
  push:
    paths:
      - 'native/android/**'

env:
  ANDROID_SECRET: ${{ secrets.STG_ANDROID_SECRET }}

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Create google-services.json
        working-directory: ./native/android/app
        run: |
          echo ${ANDROID_SECRET} > google-services.json
          echo '--- debug --------'
          cat google-services.json
          echo '------------------'

      - name: Run Unit tests
        working-directory: native/android
        run: ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Create google-services.json
        working-directory: ./native/android/app
        env:
          ANDROID_SECRET: ${{ secrets.STG_ANDROID_SECRET }}
        run: |
          echo ${ANDROID_SECRET} > google-services.json
          echo '--- debug --------'
          cat google-services.json
          echo '------------------'

      - name: Build debug APK
        working-directory: native/android
        run: ./gradlew assembleDebug --stacktrace

      - name: Create APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
