name: User API(Golang) Reviewdog
on:
  pull_request:
    paths:
      - 'api/user/**'

jobs:
  reviewdog:
    name: Reviewdog
    runs-on: ubuntu-latest

    steps:
      - name: Setup Golang 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download modules
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./api/user
        run: go mod download

      - name: Setup
        working-directory: ./api/user
        run: make setup

      - name: Reviewdog
        working-directory: ./api/user
        run:  make review REVIEWDOG_ARG="-reporter='github-pr-review'"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
